program = { definition }

definition = entry | function

entry = 'entry', stmtEnd, body, '/entry'

function = 'func', id, '(', funcList, ')', [type], stmtEnd, body, '/func'

funcList = {funcTypeParams, ','}, funcTypeParams

funcTypeParams = {id, ','}, id, type

body = {stmt}

stmt = (if | declaration | expr | return), stmtEnd

return = 'return', expr

if = 'if', expr, stmtEnd, body, '/if'
var = 'var', (mulVar | singleVar)
decl = 'decl', mulVar
stmtEnd = newLine | ';'

mulVar = varDecl,{(',', varDecl)}, type
singleVar = assign | (id, type)

varDecl = id | assign

assign = id, '=', expr

typeModifier = 'ptr'

funcType = 'func', '(', [type,{',', type}], ')', [type]

type = [typeModifier], (id | funcType)

id = letter, {(letter | cipher)}

expr = ('(', exprC, ')') | exprC

exprC =  dec | inc | id | (expr, binOp, expr) | (unOp,expr) | assign | const

const = number | string

string = '"', {letter}, '"'

number = decNumber | binNumber | hexNumber

binOp = '+' | '-' | '*' | '/' | 'and' | 'or' | '==' | '!='
unOp = '-' | '!' 
inc = id, '++'
dec = id, '--'

decNumber = ? decimal number ?
hexNumber = ? hexadecimal number like 456h, letters A-F can be both cases, h should be lowcase ?
binNumber = ? binary number like 10101b, b should be lowcase ?

letter = ? any Unicode letter ?
cipher = ? any cipher ?
newLine = ? new line delimiter ?

