#include "cgen.h"

#include "../utils/env.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void file_indent(FILE *out, uint8_t indent) {
  for (uint8_t i = 0; i < indent; ++i) {
    fputc(' ', out);
  }
}

void ccode_genBody(struct pnode *body, FILE *out, uint8_t indent);

void ccode_genRecExpr(struct pnode *root, FILE *out) {
  if (!root) {
    return;
  }

  struct token tok;
  uintptr_t val = pnode_getval(root);

  tok.type = (enum token_type) val;

  switch (root->id) {
  case PR_BINOP:
    if (array_len(root->leaves) != 2) {
      env.fail("Unacceptable len: %lu", array_len(root->leaves));
    }
    
    fputs("( ", out);    
    ccode_genRecExpr(*leaves_get(root->leaves, 0), out);
    fprintf(out, " %s ", token_str(&tok));
    ccode_genRecExpr(*leaves_get(root->leaves, 1), out);
    fputs(" )", out);
    break;

  case PR_UNOP:
    if (array_len(root->leaves) != 1) {
      env.fail("Unacceptable len: %zu", array_len(root->leaves));
    }

    fputs("( ", out);    
    fprintf(out, "%s", token_str(&tok));
    ccode_genRecExpr(*leaves_get(root->leaves, 0), out);
    fputs(" )", out);
    break;
  case PR_ID:
    fputs((char*) val, out);
    break;
  case PR_CALL: {
    size_t len = array_len(root->leaves);
    if (len < 1) {
      env.fail("Unacceptable len: %zu", len);
    }

    ccode_genRecExpr(*leaves_get(root->leaves, 0), out);
    fputc('(', out);

    for (size_t i = 1; i < len; ++i) {
      if (i - 1) {
        fputc(',', out);
      }

      ccode_genRecExpr(*leaves_get(root->leaves, 1), out);
    }

    fputc(')', out);

    break;
  }
  default:
    fprintf(out, "%ld", (intptr_t) val);
    break;

  }
  
}

void ccode_genExpr(struct pnode *expr, FILE *out, uint8_t indent) {
  file_indent(out, indent);
  ccode_genRecExpr(expr, out);
}

void ccode_genIf(struct pnode *ifNode, FILE *out, uint8_t indent) {
  file_indent(out, indent);
  fputs("if ( ", out);
  ccode_genExpr(*leaves_get(ifNode->leaves, 0), out, 0);
  fputs(" ) {\n\n", out);
  ccode_genBody(*leaves_get(ifNode->leaves, 1), out, indent + 2);
  file_indent(out, indent);
  fputs("}\n", out);
}

void ccode_genStmt(struct pnode *stmt, FILE *out, uint8_t indent) {
  switch (stmt->id) {
  case PR_IF:
    ccode_genIf(stmt, out, indent);
    break;
  default:
    ccode_genExpr(stmt, out, indent);
    fputs(";\n", out);
    break;
  }
}

char* cgen_csym(struct type *type, const char *name);

void cgen_cfuncparms(FILE *out, Array *parms) {
  size_t len = array_len(parms);

  if (!len) {
    fputs("void", out);
    return;
  }

  char *par;
  for(size_t i = 0; i < len; ++i) {
    if (i) {
      fputc(',', out);
    }

    par = cgen_csym((struct type*) *array_get(parms, i), "");
    fputs(par, out);
    free(par);
  }
}

char* cgen_csym(struct type *type, const char *name) {
  char *str;
  size_t size;
  FILE *strFile = open_memstream(&str, &size);
  if (type_isFunc(type)) {
    struct ftype *ftype = (struct ftype*) type;
    size_t pms;
    char *fmt = cgen_csym(ftype->ret, "%s"), *pm;
    FILE *pmFile = open_memstream(&pm, &pms); 
    fprintf(pmFile, fmt, "(*%s)(");
    cgen_cfuncparms(pmFile, ftype->params);
    fputc(')', pmFile);
    fclose(pmFile);
    fprintf(strFile, pm, name);
    free(pm);
  } else {
    char tmp[4096];
    fprintf(strFile, "%s %s", (type == type_none) ? "void" : type_str(type, tmp, 4096), name);
  }

  fclose(strFile);

  return str;
}

void ccode_declSyms(Symbols *syms, FILE *out, uint8_t indent) {
  
  MapIter *iter = mapiter_start(syms);

  Pair *decl;
  struct symbol *sym;
  
  while ((decl = mapiter_next(iter))) {
    sym = (struct symbol*) decl->value;
    file_indent(out, indent);
    char *csym = cgen_csym(sym->type, (char*) decl->key);
    fprintf(out, "%s%s;\n", (sym->decl ? "extern " : ""), csym);
    pair_free(decl);
    free(csym);
  }

  mapiter_free(iter);

}

void ccode_genBody(struct pnode *body, FILE *out, uint8_t indent) {
  size_t len = array_len(body->leaves);

  ccode_declSyms(pnode_getSyms(body), out, indent);

  for (size_t i = 0; i < len; ++i) {
    ccode_genStmt(*leaves_get(body->leaves, i), out, indent);
  }
}

void ccode_genEntry(struct pnode *entry, FILE *out) {

  fputs("void __helm_entry(void) {\n\n", out);

  ccode_genBody(*leaves_get(entry->leaves, 0), out, 2);

  fputs("\n}\n", out);

}

void ccode_genDef(struct pnode *def, FILE *out) {

  switch (def->id) {
  case PR_ENTRY:
    ccode_genEntry(def, out);
    break;
  default:
    env.fail("Not a definition: %s", nt_str(def->id));
    break;
  }

}

void ccode_printDefaultHeaders(FILE *out) {
  fputs("/* Generated by the helmc experimental compiler.\n"
        " * This software is experimental and should not be used except for experimental purposes.\n"
        " */\n\n", out);
  fputs("#include <stdbool.h>\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        "typedef int8_t int8;\n"
        "typedef int16_t int16;\n"
        "typedef int32_t int32;\n"
        "typedef int64_t int64;\n\n", out);
}

void cgen(struct pnode *tree, FILE *out) {

  ccode_printDefaultHeaders(out);

  if (tree->id != PR_PROGRAM) {
    env.fail("Cannot generate anything from a broken tree. Expected %s, found %s", nt_str(PR_PROGRAM), nt_str(tree->id));
  }
 
  ccode_declSyms(pnode_getSyms(tree), out, 0);

  size_t len = array_len(tree->leaves);
  for (size_t i = 0; i < len; ++i) {
    ccode_genDef(*leaves_get(tree->leaves, i), out);
  }
  
}

