#include "cgen.h"

#include "../utils/env.h"

#include <stdio.h>

void file_indent(FILE *out, uint8_t indent) {
  for (uint8_t i = 0; i < indent; ++i) {
    fputc(' ', out);
  }
}

void ccode_genBody(struct pnode *body, FILE *out, uint8_t indent);

void ccode_genRecExpr(struct pnode *root, FILE *out) {
  if (!root) {
    return;
  }

  struct token tok;
  uintptr_t val = pnode_getval(root);

  tok.type = (enum token_type) val;

  switch (root->id) {
  case PR_BINOP:
    if (array_len(root->leaves) != 2) {
      env.fail("Unacceptable len: %lu", array_len(root->leaves));
    }
    
    ccode_genRecExpr(*leaves_get(root->leaves, 0), out);
    fprintf(out, " %s ", token_str(&tok));
    ccode_genRecExpr(*leaves_get(root->leaves, 1), out);
    break;

  case PR_UNOP:
    if (array_len(root->leaves) != 1) {
      env.fail("Unacceptable len: %lu", array_len(root->leaves));
    }
    
    fprintf(out, "%s", token_str(&tok));
    ccode_genRecExpr(*leaves_get(root->leaves, 0), out);
    break;
  case PR_ID:
    fputs((char*) val, out);
    break;
  default:
    fprintf(out, "%ld", (intptr_t) val);
    break;

  }
  
}

void ccode_genExpr(struct pnode *expr, FILE *out, uint8_t indent) {
  file_indent(out, indent);
  ccode_genRecExpr(expr, out);
}

void ccode_genIf(struct pnode *ifNode, FILE *out, uint8_t indent) {
  file_indent(out, indent);
  fputs("if ( ", out);
  ccode_genExpr(*leaves_get(ifNode->leaves, 0), out, 0);
  fputs(" ) {\n\n", out);
  ccode_genBody(*leaves_get(ifNode->leaves, 1), out, indent + 2);
  file_indent(out, indent);
  fputs("}\n", out);
}

void ccode_genStmt(struct pnode *stmt, FILE *out, uint8_t indent) {
  switch (stmt->id) {
  case PR_IF:
    ccode_genIf(stmt, out, indent);
    break;
  default:
    ccode_genExpr(stmt, out, indent);
    fputs(";\n", out);
    break;
  }
}

void ccode_declSyms(Symbols *syms, FILE *out, uint8_t indent) {
  
  MapIter *iter = mapiter_start(syms);

  Pair *decl;
  
  while ((decl = mapiter_next(iter))) {
    file_indent(out, indent);
    fprintf(out, "%s %s;\n", (char*) decl->value, (char*) decl->key);
    pair_free(decl);
  }

  mapiter_free(iter);

}

void ccode_genBody(struct pnode *body, FILE *out, uint8_t indent) {
  size_t len = array_len(body->leaves);

  ccode_declSyms(pnode_getSyms(body), out, indent);

  for (size_t i = 0; i < len; ++i) {
    ccode_genStmt(*leaves_get(body->leaves, i), out, indent);
  }
}

void ccode_genEntry(struct pnode *entry, FILE *out) {

  fputs("void __helm_entry(void) {\n\n", out);

  ccode_genBody(*leaves_get(entry->leaves, 0), out, 2);

  fputs("\n}\n", out);

}

void ccode_genDef(struct pnode *def, FILE *out) {

  switch (def->id) {
  case PR_ENTRY:
    ccode_genEntry(def, out);
    break;
  default:
    env.fail("Not a definition: %s", nt_str(def->id));
    break;
  }

}

void ccode_printDefaultHeaders(FILE *out) {
  fputs("/* Generated by the helmc experimental compiler.\n"
        " * This software is experimental and should not be used except for experimental purposes.\n"
        " */\n\n", out);
  fputs("#include <stdbool.h>\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        "typedef int8_t int8;\n"
        "typedef int16_t int16;\n"
        "typedef int32_t int32;\n"
        "typedef int64_t int64;\n\n", out);
}

void cgen(struct pnode *tree, FILE *out) {

  ccode_printDefaultHeaders(out);

  if (tree->id != PR_PROGRAM) {
    env.fail("Cannot generate anything from a broken tree. Expected %s, found %s", nt_str(PR_PROGRAM), nt_str(tree->id));
  }
  
  size_t len = array_len(tree->leaves);
  for (size_t i = 0; i < len; ++i) {
    ccode_genDef(*leaves_get(tree->leaves, i), out);
  }
  
}

